### ISSUE TITLE
Whitelist dont work!

### ISSUE THREAD

**Issue by gioiliop7** [usefulteam/jwt-auth#105]
I use the plugin for two months and the whitelist for the endpoints worked well. But from today the whitelist doesn't work and i have issues because in some endpoints the wp-json ask me for authorization header.
I send you the whitelist function
`add_filter('jwt_auth_whitelist', function ($endpoints) {
    $whitelistedEndpoints = array(
        '/wp-json/api/v1/register-user/',
        '/wp-json/dokan/v1/*',
    );
    return array_unique(array_merge($endpoints, $whitelistedEndpoints));});`

Thank you

**Comment by sun** [comment]
Did you add or remove any plugins, update any plugins, or change any configuration?

**Comment by gioiliop7** [comment]
I don't remember but the plugins i have used and i am using today, make another work, they don't affect authentication and requests.
But, i have dokan which works with wp-json and i can't make it work with the jwt plugin because i cant get a response for the vendors as an example.
May be the htcaccess? I dont think so but..
The requests with jwt when they have token, work but the whitelist not..

**Comment by gioiliop7** [comment]
Try to change htcaccess, nothing worked. The problem is with the whitelist function. Maybe wants priority?

**Comment by sun** [comment]
I would recommend to go back to the last known working version/state of the site from backups. Afterwards you can redo the changes you were doing and test more frequently at what point it stops working.

Beyond that I don't see how the jwt-auth plugin would be the cause of issues, so I would suggest to close this issue.

The only additional pointer I can give you is that we removed the whitelist feature entirely from the new major version v3 that is (only) available on GitHub currently. This version is not available on WordPress.org yet, so you would only have it if you manually downloaded and installed the plugin from the source.

**Comment by gioiliop7** [comment]
So in the new version how to whitelist endpoints?

**Comment by sun** [comment]
> So in the new version how to whitelist endpoints?

The whitelist has been removed altogether, so every endpoint of the REST API is reachable normally.  The jwt-auth plugin no longer manipulates the access beyond the regular built-in access system of all endpoints.

**Comment by gioiliop7** [comment]
Problem solved. There is a conflict with the plugin, WPForms Lite. 
I removed it and the whitelist works fine. Thank you.
