### ISSUE TITLE
Passwords with special characters don't work

### ISSUE THREAD

**Issue by davidhealey** [usefulteam/jwt-auth#106]
A password such as ,;:./?+-_*!”£$%^&() works via wordpress login, but fails with JWT Auth. What’s the solution?

**Comment by pesseba** [comment]
I tested it and the password supplied works...

![image](https://github.com/usefulteam/jwt-auth/assets/23182168/273ad225-e9bf-42a5-b828-5a9f64279fb9)

**Comment by davidhealey** [comment]
Thank you. For anyone else, this has lead me to figure out that the issue I'm having is caused by the mod security rules of my server.

**Comment by RpGmAx** [comment]
Hi,

I have the same problem but only with apostrophes.

Fixed with a change in class-auth.php, addslashes fx added (like I did before on the wp-api-jwt-auth plugin).
$user = wp_authenticate($username, addslashes($password));

@pesseba can you check ?

Thank you :)
