### ISSUE TITLE
Algorithm not allowed — jwt_auth_invalid_token

### ISSUE THREAD

**Issue by bassamBS** [usefulteam/jwt-auth#110]
Hello, 

I've done some research on the issues, but unfortunately, I couldn't find a solution.

The endpoint /wp-json/jwt-auth/v1/token is working as expected and returns "jwt_auth_valid_credential."

However, when I try to create a user using the endpoint wp-json/wp/v2/users, I'm encountering the following issue:

```
{
    "success": false,
    "statusCode": 403,
    "code": "jwt_auth_invalid_token",
    "message": "Algorithm not allowed",
    "data": []
}
```

The related call: 

```
curl --location 'https://my-wordpress.com/wp-json/wp/v2/users' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer [TOKEN CREATED]' \
--data-raw '{
    "username": "test",
    "email": "test@gmail.com",
    "password": "test"
}'
```

 I've installed the plugin and have added the JWT_AUTH_SECRET_KEY to the wp-config.php file nothing more.

**Comment by bassamBS** [comment]
Yes, my client has a lot of plugins... 
![plugin-first-page](https://github.com/usefulteam/jwt-auth/assets/87444448/8f19b6e9-5175-4732-af9a-395fd3eb44e5)
![plugin-second-page](https://github.com/usefulteam/jwt-auth/assets/87444448/75c587ac-3f18-43ea-b3c4-47112935b8ab)

**Comment by dominic-ks** [comment]
@bassamBS OK, then I'd potentially check if one of them is using the firebase jwt lib. I'm not sure if it'd be that issue or not, but we have an issue open for that but a solution has not been agreed - https://github.com/usefulteam/jwt-auth/issues/82

**Comment by bassamBS** [comment]
OK, thank you for your quick answer

**Comment by bassamBS** [comment]
I found nothing related to Firebase jwt lib

**Comment by dominic-ks** [comment]
@bassamBS OK, well I am happy to help but will need some information that would help me reproduce the issue. e.g. information about the environment, or some level of troubleshooting information, primarily, it could still be a conflict with another plugin, and so we'd need to identify which one, which would require deactivating plugins on the site to see if the issue persisted, and if not, reactivating them one by one to find the conflict.

**Comment by dominic-ks** [comment]
Hey @bassamBS did you find a solution to your issue?
