### ISSUE TITLE
Fatal error on plugin activation

### ISSUE THREAD

**Issue by aranwilcox** [usefulteam/jwt-auth#12]
Not sure why this is happening as there is no additional error.

I am trying to set up JWT Auth on a local docker container and I cannot seem to activate the plugin. I get the following error message:

![screenshot-localhost_9998-2020 09 11-11_14_56](https://user-images.githubusercontent.com/12252963/92910705-38f60700-f420-11ea-9a38-f73ae28edf7c.png)

I am able to install and activate other plugins so I wondering what the reason is. I am using WP 5.5.1

Any help is appreciated.

**Comment by aranwilcox** [comment]
I later found that there is a composer file that needs installing, after that the plugin activated correctly.

**Comment by contactjavas** [comment]
Hi @aranwilcox , did you install the plugin by downloading from GitHub? (Not through WordPress plugin repository)
I ignore [vendor dir](https://github.com/usefulteam/jwt-auth/blob/master/.gitignore) in GitHub. So people need to run `composer update`.

**Comment by aranwilcox** [comment]
Thanks Bagus! That did resolve my issue, I will close the issue 👍
