### ISSUE TITLE
Redirection on Invalid Credentials

### ISSUE THREAD

**Issue by asadamatic** [usefulteam/jwt-auth#129]
I'm facing an issue where the `/token` endpoint is redirection on invalid credentials and returns html in the response instead of the json response. It works fine on valid credentials.

I'm facing the same issue with the other [JWT Authentication](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) plugin.

**Comment by dominic-ks** [comment]
Hello, do you get this same issue if testing the plugin with no other plugins enabled / default theme?

**Comment by asadamatic** [comment]
We checked by disabling all plugins and it worked. There's probably some conflict issue.

**Comment by dominic-ks** [comment]
@asadamatic did you find out what the conflict was? If so please share as it may help others.

**Comment by asadamatic** [comment]
I'm yet to test it for conflict.
