### ISSUE TITLE
Output user data from custom endpoint

### ISSUE THREAD

**Issue by samueleastdev** [usefulteam/jwt-auth#14]
Hi 

I am probably missing something obvious by how to I get the user data of an authenticated user in a custom endpoint?

~~~
function get_user_data( $response ) {

	// HOW DO I OUTPUT USER DATA HERE?
	error_log(print_r($response, true));
 
  	return 'User';
}


add_action( 'rest_api_init', function () {
  register_rest_route( 'access/v1', '/content/(?P<id>\d+)', array(
    'methods' => 'GET',
    'callback' => 'get_user_data',
    'args' => array(
      'id' => array(
        'validate_callback' => function($param, $request, $key) {
          return is_numeric( $param );
        }
      ),
    ),
  ) );
} );
~~~

It is validating successful and I am getting the response but I am not sure how to parse the token to get the user data?

I know with another plugin you do this.
~~~
$user = JWTAuth::parseToken()->authenticate()
~~~

Thanks

**Comment by kosso** [comment]
Whenever you have the means to make an authenticated request to Wordpress (JWT or OAuth2 etc.), you *should* be able to make an authenticated request to `/wp-json/wp/v2/users/me` to get the data about that user.

**Comment by contactjavas** [comment]
Hi @samueleastdev , 

Actually, if you pass a correct bearer token to your request, then you can just use something like `wp_get_current_user()` as usual.
I've just tested it.

Let me close this issue. If you still have question, feel free to post it here again :)
