### ISSUE TITLE
Whitelisting isn't implemented at all?

### ISSUE THREAD

**Issue by rw3iss** [usefulteam/jwt-auth#15]
Hello,

 We're using this plugin (v1.2.6), and it mentions in the documentation of adding a whitelist filter:

add_filter( 'jwt_auth_whitelist', function ( $endpoints ) { return array(...); });

However, I've implemented this, and after looking into why it wasn't working, it seems that this filter isn't called anywhere whatsoever in the plugin code, nor is the word 'whitelist' mentioned anywhere in the code. So is this not implemented within the plugin at all, or are we to use it differently or manually ourselves?

I tried moving the filter definition around to the beginning of the initialization code, as the documentation suggests, but it still doesn't seem to do anything.

I had to implemented my own whitelisting logic in the class-jwt-auth-public.php determine_current_user function.

**Comment by contactjavas** [comment]
Hi @rw3iss , the plugin version is `1.4.2`. And we never have `1.2.6`. 

I think you're using [jwt-authentication-for-wp-rest-api](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api) (which has `1.2.6`) instead of [jwt-auth](https://wordpress.org/plugins/jwt-auth/) plugin :)

Can you please check?

**Comment by contactjavas** [comment]
yea, and we don't have `class-jwt-auth-public.php` file, so yea.. you're using different plugin ([jwt-authentication-for-wp-rest-api](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/)).

This repo is for [jwt-auth](https://wordpress.org/plugins/jwt-auth/) plugin :)

**Comment by rw3iss** [comment]
Shit, sorry 😜 thank you.
