### ISSUE TITLE
adding oembed endpoint to  jwt_auth_default_whitelist since it used by gutenberg editor

### ISSUE THREAD

**Issue by omarkhatibco** [usefulteam/jwt-auth#17]
Hi,

I ran into a problem in Gutenberg editor where Oembed blocks like youtube, instagram & others does not show any prelive in gutenberg.

after some investigation I saw the response is `jwt_auth_no_auth_header`.

so I think `'/wp-json/oembed/*` should be added to `jwt_auth_default_whitelist`  as it used internally by WP.

**Comment by ggoyanes** [comment]
I'm having the same problem but adding `'/wp-json/oembed/*'` on `jwt_auth_whitelist` is not working for me.

**Comment by omarkhatibco** [comment]
Hi @ggoyanes ,

I do solved it temporary by adding a file in `wp-content/mu-plugins/jwt_auth_whitelist.php`
with this code 

```php
<?php

add_filter('jwt_auth_whitelist', function ($endpoints) {
	return [
		'/wp-json/oembed/*',
	];
});
```

**Comment by ggoyanes** [comment]
Thanks @omarkhatibco ! That works!

**Comment by contactjavas** [comment]
Thanks @omarkhatibco & @ggoyanes ! :)
Now i include it in default whitelist. Should be part of next release.
