### ISSUE TITLE
Plugin causing Javascript issues on other plugins

### ISSUE THREAD

**Issue by tibidibtibo** [usefulteam/jwt-auth#21]
I have some troubles with 'jwt-auth' on my website using Theme X.

When I try to open the Theme X editor (<url>/x/theme-options), it fails with the followings javascript errors : 

In one picture :
![image](https://user-images.githubusercontent.com/10530128/103551012-fdd58300-4ea9-11eb-9d20-1c7b1c1ac8dd.png)

Here is the text :
```
app.514eb0c.js:42 

Failed to inflate gzip data buffer error
```
```
app.514eb0c.js:42 

TypeError: Cannot read property 'groups' of undefined
    at app.514eb0c.js:42
    at r (lodash.min.js?ver=4.17.19:88)
    at db (app.514eb0c.js:42)
```
```
react-dom.min.js?ver=16.13.1:125 

TypeError: Cannot read property 'reduce' of undefined
    at app.514eb0c.js:42
    at r (lodash.min.js?ver=4.17.19:88)
    at app.514eb0c.js:42
    at r (lodash.min.js?ver=4.17.19:88)
    at app.514eb0c.js:42
    at r (lodash.min.js?ver=4.17.19:88)
    at Ia (app.514eb0c.js:42)
    at app.514eb0c.js:42
    at app.514eb0c.js:42
    at Object.useMemo (react-dom.min.js?ver=16.13.1:216)
```
```
app.514eb0c.js:42 

Uncaught (in promise) TypeError: Cannot read property 'reduce' of undefined
    at app.514eb0c.js:42
    at r (lodash.min.js?ver=4.17.19:88)
    at app.514eb0c.js:42
    at r (lodash.min.js?ver=4.17.19:88)
    at app.514eb0c.js:42
    at r (lodash.min.js?ver=4.17.19:88)
    at Ia (app.514eb0c.js:42)
    at app.514eb0c.js:42
    at app.514eb0c.js:42
    at Object.useMemo (react-dom.min.js?ver=16.13.1:216)
```
I seems that is a mess in the javascript resources ! I desactivated all others plugins on my website and only 'jwt-auth' is causing this issue.

`app.514eb0c.js` is a static file from Cornerstone, a plugin used by Theme X to edit pages. The location is : `/www/wp-content/plugins/cornerstone/assets/dist/js`

Is anything the plugin trying to minify or uglify ? Is there a dependencies conflict (lodash ? react ?) ?
I looked at the plugin's code but I'm not really good in PHP ^^

Any idea ?

Thanks !

**Comment by contactjavas** [comment]
Hi @tibidibtibo , I can't go deeper for now, but this JWT-Auth plugin has nothing to do with JavaScript directly.
But if the theme is doing some REST API request to your site via custom endpoint, then you might need to whitelist them.
There is a whitelisting section in the doc you can use for now.

**Comment by tibidibtibo** [comment]
> Hi @tibidibtibo , I can't go deeper for now, but this JWT-Auth plugin has nothing to do with JavaScript directly.
> But if the theme is doing some REST API request to your site via custom endpoint, then you might need to whitelist them.
> There is a whitelisting section in the doc you can use for now.

Thanks ! 

You're right, the problem was on api internal request.

I was trapped by another request "successful but not" !

- code 200 :
![image](https://user-images.githubusercontent.com/10530128/103627506-037ca880-4f3e-11eb-931e-7f1cd6896cce.png)

- but code 403 in data 
![image](https://user-images.githubusercontent.com/10530128/103627416-df20cc00-4f3d-11eb-867a-1529961c0756.png)

Adding this endpoint to whitelist fixed it :-)
