### ISSUE TITLE
how to add custom rest api routes via single plugin file?

### ISSUE THREAD

**Issue by mrmmg** [usefulteam/jwt-auth#32]
Hi

i have created a single file plugin and named it as jwt-auth-routes and upload it into plugins directory of wordpress and finally activate the plugin through wordpress admin panel but my custom routes returns 403 with message "JWT is not configurated properly."

my plugin information:

plugin file name: `jwt_auth_routes.php`

code:

```
/**
* wordpress comments and plugin name & etc.
*/

defined( 'ABSPATH' ) || die( "Can't access directly" );

$routes = [
	'/wp-json/hm/v1/*'
];

add_filter( 'jwt_auth_whitelist', function ( $endpoints ) {
	
    return $routes;
	
});
```

BUT IT's NOT WORKING. the other routes such as /token and /token/validate are working and the generated token is valid.

please help me.

**Comment by pesseba** [comment]
I use this filter as follow:

```
add_filter( 'jwt_auth_whitelist', function ( $endpoints ) {
	
    array_push($endpoints,'/wp-json/hm/v1/*');
    return $endpoints;
	
});
```

**Comment by mrmmg** [comment]
@pesseba 

It's work

Thanks you

**Comment by mrmmg** [comment]
@pesseba 

i added this code to function.php (theme file) and it's not work.

code is:

```

add_filter( 'jwt_auth_whitelist', function ( $endpoints ) {

    array_push($endpoints,'/wp-json/hm/v1/createUser');
    return $endpoints;

});

```

and i tried this code:

```
function add_custom_route_to_jwt_auth($endpoints){
	
	array_push($endpoints, '/wp-json/hm/v1/createUser');
    return $endpoints;
	
}

add_filter( 'jwt_auth_whitelist' , 'add_custom_route_to_jwt_auth', 10, 1);
```

**Comment by pesseba** [comment]
Hi @mrmmg , Maybe functions.php is not a good place to use rest api hooks. I'm not sure, but this is a template file, and rest api calls doesn't load template files, so wordpress could be skipping this.
I think rest api is better extensible by plugins then themes...

**Comment by mrmmg** [comment]
so, you suggest me to make a plugin and handle all rest api token and jwt
auth with a plugin.
nice idea... I have to learn developing wordpress plugin

thanks you :)
