### ISSUE TITLE
Wrong repo link on packagist

### ISSUE THREAD

**Issue by askovdal** [usefulteam/jwt-auth#37]
The package on packagist ([link](https://packagist.org/packages/usefulteam/jwt-auth)) uses **ogabrielaraujo** instead of **usefulteam**, which results in a 404 when downloading the package via composer.

**Comment by pesseba** [comment]
Looks like a fork that doesn't exist anymore...
The oficial location of this plugin is here: https://github.com/usefulteam/jwt-auth
And in WP plugin repository: https://br.wordpress.org/plugins/jwt-auth/

**Comment by contactjavas** [comment]
Let me close this since it's already pointing to this repo :)
Thanks
