### ISSUE TITLE
token not verified for first time login for new registered users

### ISSUE THREAD

**Issue by virajsoni06** [usefulteam/jwt-auth#38]
If a new registered user attempts to validate the token, it sends `jwt_auth_obsolete_token` only the first time and any subsequent login token validation works fine.

![image](https://user-images.githubusercontent.com/13236286/131341710-a458b8ad-7a46-4af6-8775-9ade67945941.png)

**Comment by pesseba** [comment]
Hi @virajsoni06, I couldn't reproduce the problem here....

**Comment by holygekko** [comment]
I'm having the same problem. Added a detailed step by step here: https://github.com/usefulteam/jwt-auth/issues/35#issuecomment-912558084

**Comment by pesseba** [comment]
Hi @holygekko I fixed the problem. Please test the last version: https://github.com/usefulteam/jwt-auth/commit/f55faf712fb28cf14ce519c80ba28a168cf254cc
