### ISSUE TITLE
What's the relation between this plugin and JWT Authentication for WP REST API?

### ISSUE THREAD

**Issue by ciriousjoker** [usefulteam/jwt-auth#42]
This plugin: https://wordpress.org/plugins/jwt-auth
The other plugin: https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api

**Comment by contactjavas** [comment]
Hi @CiriousJoker , thanks for asking.

The codebase for "jwt-auth" was based on "jwt-authentication-for-wp-rest-api".
Thanks them for the great work.

Then the "jwt-auth" is improved by contributors.
