### ISSUE TITLE
Whitelist route and method http

### ISSUE THREAD

**Issue by cedricDevWP** [usefulteam/jwt-auth#46]
Hi,

It's possible to whitelist route and method http ?

for example : 

GET /users => No whitelist
POST /users => Whitelist

if this is not possible, is it possible to consider implementing this feature?

Thx,
Cédric

**Comment by cedricDevWP** [comment]
I created a pull request => #47

**Comment by contactjavas** [comment]
thanks @cedricDevWP , merged
