### ISSUE TITLE
Error: Authorization header malformed.

### ISSUE THREAD

**Issue by e-labInnovations** [usefulteam/jwt-auth#68]
I followed your documentation and I can generate the token. But the generated token is not working 😥

![image](https://user-images.githubusercontent.com/33958126/174468449-4565a16f-d285-4043-ae0f-5c3205c58ed4.png)

I got a response like this when I tried to use generated token.
``` json
{
    "success": false,
    "statusCode": 403,
    "code": "jwt_auth_bad_auth_header",
    "message": "Authorization header malformed.",
    "data": []
}
```

![image](https://user-images.githubusercontent.com/33958126/174468313-30ddbd2d-d0bf-4c5b-a537-0f73a5dc5adb.png)
![image](https://user-images.githubusercontent.com/33958126/174468369-65e9d35f-a3ad-4f71-b245-b051c7219e08.png)
![image](https://user-images.githubusercontent.com/33958126/174647835-06646f70-b04a-4737-8723-d8b9ca6855d1.png)

**Comment by pesseba** [comment]
Make sure the .htaccess has the right configuration

**Comment by e-labInnovations** [comment]
content of my `.htaccess` file is below

``` htaccess
# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
</IfModule>

# END WordPress
# php -- BEGIN cPanel-generated handler, do not edit
# Set the “ea-php72” package as the default “PHP” programming language.
<IfModule mime_module>
  AddHandler application/x-httpd-ea-php72 .php .php7 .phtml
</IfModule>
# php -- END cPanel-generated handler, do not edit
```

**Comment by e-labInnovations** [comment]
Fixed
Problem due to postman Authorization problem.
For fixing, selected `No Auth` in the `Authorization Type` option
