### ISSUE TITLE
PHP Warning:  Undefined property: stdClass::$pass in jwt-auth/class-devices.php on line 100

### ISSUE THREAD

**Issue by alexx855** [usefulteam/jwt-auth#72]
im just getting alot of these warnings, can i open a pr to that fix this?

thanks

**Comment by dominic-ks** [comment]
Hey @alexx855 are you still seeing these warnings as I don't think I can see them.

**Comment by sun** [comment]
> can i open a pr to that fix this?

Of course, you are always free to contribute to the plugin! 🙂

**Comment by alexx855** [comment]
Im not seeing it anymore too, i will need to do some deep debug, if i found something or the issue i'll open a PR.

thanks!
