### ISSUE TITLE
Contact Form 7 Is Broken When JWT Auth Active

### ISSUE THREAD

**Issue by saqib6161** [usefulteam/jwt-auth#77]
When my JWT Auth plugin is active then it broke all forms in our website. When I deactivate the plugin it starts working again I tried uninstalling and reinstalling the actual plugin functionality is working fine I am able to login using the API has anyone else had the same problem? I am using for API Login through our app.

**Comment by dominic-ks** [comment]
Hey @saqib6161 first guess would be that you need to check the whitelisting section from the readme and whitelist the API namespace for Contact Form 7 and anything else you need:

 - [https://github.com/usefulteam/jwt-auth#whitelisting-endpoints](https://github.com/usefulteam/jwt-auth#whitelisting-endpoints)

**Comment by sun** [comment]
Duplicate of #31
