### ISSUE TITLE
Latest 2.1.2 breaks my Wordpress / WooCommerce page with a fatal error

### ISSUE THREAD

**Issue by c7nj7n** [usefulteam/jwt-auth#80]
The issue that's pointed out seems to be connected to a missing file:

`wp-content/plugins/jwt-auth/vendor/composer/platform_check.php`

I managed to reproduce locally, if you need further help to debug please reach out.

**Comment by adambichler** [comment]
@c7nj7n got the same problem and reported it just yet – seems like you were quicker ;-) 

Issue #81

**Comment by dominic-ks** [comment]
Yep thanks for that both, looks like some files haven't gone into the wp,org repo for some reason, fixing it now.

**Comment by dominic-ks** [comment]
@c7nj7n @adambichler just pushed version 2.1.3 to WordPress.org and should fix this, take it for a spin and let me know!

**Comment by c7nj7n** [comment]
That was a quick fix, awesome job @dominic-ks ! I just upgraded to 2.1.3 and it's all smoothed out. Thank you and keep up the good work!
