### ISSUE TITLE
register_rest_route was called incorrectly

### ISSUE THREAD

**Issue by simplenotezy** [usefulteam/jwt-auth#9]
Since latest version 5.5 I am now getting error:

`{"type":1024,"message":"register_rest_route was called <strong>incorrectly&lt;\/strong&gt;. The REST API route definition for <code>jwt-auth\/v1\/token&lt;\/code&gt; is missing the required <code>permission_callback&lt;\/code&gt; argument. For REST API routes that are intended to be public, use <code>__return_true&lt;\/code&gt; as the permission callback. Please see <a href="https:\/\/wordpress.org\/support\/article\/debugging-in-wordpress\/">Debugging in WordPress&lt;\/a&gt; for more information. (This message was added in version 5.5.0.)","file":"\/Users\/me\/Projects\/project\/wp-includes\/functions.php","line":5225}`

**Comment by simplenotezy** [comment]
Related to other plugin: https://github.com/Tmeister/wp-api-jwt-auth/issues/207

**Comment by contactjavas** [comment]
Hi @simplenotezy , this permission_callback is implemented in master branch, but it's not in the WP Plugin repo yet.
Gonna push an update soon

**Comment by contactjavas** [comment]
Alright, now it's pushed to the WP plugin repo. You might want to update it :)
Thanks for your time reporting this
